services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
          - SECRET_KEY=django-insecure-2e%cv8#27v!1-=m@uw_hus%ap%+@(q@j6_ur)ynes_q_$$qa3cb
          - DEBUG=1
        volumes:
          - .:/code
        ports:
          - 8000:8000
        depends_on:
          - db
    db:
      image: postgres:17
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
